seed: 42
wandb:
  use_wandb: False
  project: "CDSG-experiments"
  entity: "ipab-rad"
data:
  dataset_name: "ipab-rad/driving_scenarios"
model:
  model_name: "codellama/CodeLlama-7b-Instruct-hf"
  random_examples: False
  retriever_model_name: "BAAI/bge-small-en-v1.5"
  client: "http://goya.inf.ed.ac.uk:8080" # on-site machine
  retrieval_top_k: 3
  decoding_top_k: 50
  temperature: 0.001
  do_sample: False
  num_beams: 1
  max_new_tokens: 1200
  max_length: 8000
  exceptions:
    do_feeding: True
    max_trials: 3
conv:
  assets:
    user: "assets/app_data/user.png"
    bot: "assets/app_data/bot.png"
  scenarios:
    path: "assets/app_data"
    bypassing: 2
    intersection: 2
    pedestrian: 2
  max_instructions: 5
  share: False