# standard libraries
import random
# Experiment tracking
import wandb
import hydra
from hydra.core.config_store import ConfigStore
from config import ExpConfig
from omegaconf import OmegaConf
# ML libraries
import torch
from datasets import load_dataset
import evaluate
from transformers import BitsAndBytesConfig, AutoModelForCausalLM, AutoTokenizer
# silence the warning 
import warnings
# Filter out the specific warning generated by the carla package
warnings.filterwarnings("ignore", message="the \"carla\" package is not installed;")
# Prompt Engineering
from utils import make_code_prompt, generate_program, run_simulation
from perplexity_with_local_model import PerplexityWithLocalModel


# Evaluation metrics
blue_metric = evaluate.load("sacrebleu")
rouge_metric = evaluate.load("rouge")
#perprexity_metric = evaluate.load("perplexity", module_type="metric")
perplexity_metric = PerplexityWithLocalModel()
    
def compute_metrics(prediction, reference, model, tokenizer):
    scores = {
        "BLEU": blue_metric.compute(predictions=[prediction],
                                    references=[reference])["score"],
        "ROUGE-L": rouge_metric.compute(predictions=[prediction],
                                        references=[reference])["rougeL"]*100,
        "SELF_PERPLEXITY": perplexity_metric.compute(predictions=[prediction],
                                        model=model, tokenizer=tokenizer)["mean_perplexity"],
        "REFERENCE_PERPLEXITY": perplexity_metric.compute(predictions=[reference],
                                        model=model, tokenizer=tokenizer)["mean_perplexity"],
        }
    print(scores, flush=True)
    return scores

cs = ConfigStore.instance()
cs.store(name="base_config", node=ExpConfig)

@hydra.main(config_path="../config", config_name="default", version_base=None)
def main(cfg: ExpConfig):
    """Code Generation Experiments"""

    if cfg.wandb.use_wandb:
        config = OmegaConf.to_container(cfg, resolve=False)
        feed = "-error-feeding" if cfg.model.exceptions.do_feeding else ""
        wandb.init(project=cfg.wandb.project,
                   entity=cfg.wandb.entity,
                   name=f"EVAL-GEN-{cfg.model.model_name}{feed}",
                   config=config)
        
    random.seed(cfg.seed)

    dataset = load_dataset(cfg.data.dataset_name,
                           trust_remote_code=True)["train"]
    d2p = {d: p for d, p in zip(dataset["description"], dataset["program"])}

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )
    #bnb_config = None

    model = AutoModelForCausalLM.from_pretrained(cfg.model.model_name,
                                                device_map="auto",
                                                quantization_config=bnb_config,
                                                torch_dtype=torch.float16,
                                                trust_remote_code=False,
                                                revision="main")
    tokenizer = AutoTokenizer.from_pretrained(cfg.model.model_name,
                                              use_fast=True)

    model.eval()

    for target_description, target_program in d2p.items():

        other_d2p = {d: p for d, p in d2p.items() if d != target_description}
        
        prompt = make_code_prompt(cfg, target_description, other_d2p)

        pred_program, compiled = generate_program(cfg, prompt, target_description, model, tokenizer)

        #compiled = run_simulation(pred_program)
    
        ## logging
        if cfg.wandb.use_wandb:
            metrics = compute_metrics(pred_program,
                                      target_program,
                                      model, tokenizer)
            stimuli = {
                "description": wandb.Html(target_description),
                "prompt": wandb.Html(prompt),
                "pred_program": wandb.Html(pred_program),
                "target": wandb.Html(target_program),
            }
            compiled["exception"] =  wandb.Html(str(compiled["exception"]))
            wandb.log({**metrics, **stimuli, **compiled})

if __name__ == "__main__":
    main()
