# standard libraries
import re
import random
from types import SimpleNamespace
# Experiment tracking
import wandb
import hydra
from hydra.core.config_store import ConfigStore
from config import ExpConfig
from omegaconf import OmegaConf
# ML libraries
import torch
from datasets import load_dataset
import evaluate
from transformers import BitsAndBytesConfig, AutoModelForCausalLM, AutoTokenizer
# Scenic compilation for evaluation
from scenic import scenarioFromString
# silence the warning 
import warnings
# Filter out the specific warning generated by the carla package
warnings.filterwarnings("ignore", message="the \"carla\" package is not installed;")
# Prompt Engineering
from utils import make_code_prompt, make_examplars, postprocess, add_exception, generate_program_from_prompt, random_examplars




# Evaluation metrics
blue_metric = evaluate.load("bleu")
rouge_metric = evaluate.load("rouge")
perprexity_metric = evaluate.load("perplexity", module_type="metric")

def try_compile(program):
    """try to compile the program if correct return 1 else 0 with exception message"""
    try:
        scenarioFromString(program)
        return {"compiled": 1, "exception": ""}
    except Exception as e :
        return {"compiled": 0, "exception": e}
    
def compute_metrics(prediction, reference, model_name):
    return {
        "BLEU": blue_metric.compute(predictions=[prediction],
                                    references=[reference])["bleu"]*100,
        "ROUGE-L": rouge_metric.compute(predictions=[prediction],
                                        references=[reference])["rougeL"]*100,
        "PP": perprexity_metric.compute(predictions=[prediction],
                                        model_id=model_name)["mean_perplexity"],
        }



cs = ConfigStore.instance()
cs.store(name="base_config", node=ExpConfig)

@hydra.main(config_path="../config", config_name="default", version_base=None)
def main(cfg: ExpConfig):
    """Code generation experiments"""

    if cfg.wandb.use_wandb:
        config = OmegaConf.to_container(cfg, resolve=False)
        feed = "-feed" if cfg.model.exceptions.do_feeding else ""
        wandb.init(project=cfg.wandb.project,
                   entity=cfg.wandb.entity,
                   name=f"GEN-{cfg.model.model_name}-{cfg.data.evaluation}{feed}",
                   config=config)
        
    random.seed(cfg.seed)

    dataset = load_dataset(cfg.data.dataset_name,
                           trust_remote_code=True)["train"]
    d2p = {d: p for d, p in zip(dataset["description"], dataset["program"])}

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    model = AutoModelForCausalLM.from_pretrained(cfg.model.model_name,
                                                device_map="auto",
                                                quantization_config=bnb_config,
                                                torch_dtype=torch.float16,
                                                trust_remote_code=False,
                                                revision="main")
    tokenizer = AutoTokenizer.from_pretrained(cfg.model.model_name,
                                              use_fast=True)

    model.eval()


    for target_description, target_program in d2p.items():

        other_d2p = {d: p for d, p in d2p.items() if d != target_description}
        examplars = make_examplars(cfg, target_description, other_d2p)
        
        prompt = make_code_prompt(target_description, examplars, d2p)
        
        num_trials = 0
        while True:
            num_trials += 1

            pred_program, pred_output = generate_program_from_prompt(cfg, model, tokenizer, prompt)
            compiled = try_compile(pred_program)

            print(compiled["compiled"])
            
            if not compiled["compiled"] and \
                cfg.model.exceptions.do_feeding and \
                num_trials < cfg.model.exceptions.max_trials:
                prompt = add_exception(pred_output, compiled["exception"])
            else:
                break

        ## logging
        if cfg.wandb.use_wandb:
            metrics = compute_metrics(pred_program, target_program, cfg.model.model_name)
            stimuli = {
                "description": wandb.Html(target_description),
                "prompt": wandb.Html(prompt),
                "pred_program": wandb.Html(pred_program),
                "target": wandb.Html(target_program),
            }
            compiled["exception"] =  wandb.Html(str(compiled["exception"]))
            wandb.log({**metrics, **stimuli, **compiled})

if __name__ == "__main__":
    main()
