# standard libraries
import re
import random
# Experiment tracking
import wandb
import hydra
from omegaconf import DictConfig, OmegaConf
# ML libraries
import torch
from datasets import load_dataset
import evaluate
from transformers import BitsAndBytesConfig, AutoModelForCausalLM, AutoTokenizer
# Scenic compilation for evaluation
from scenic import scenarioFromString
# silence the warning 
import warnings
# Filter out the specific warning generated by the carla package
warnings.filterwarnings("ignore", message="the \"carla\" package is not installed;")
# Prompt Engineering
from prompting import make_prompt, retrieve_examplars, postprocess, add_exception

# Evaluation metrics
blue_metric = evaluate.load("bleu")
rouge_metric = evaluate.load("rouge")
exact_match_metric = evaluate.load("exact_match")
perprexity_metric = evaluate.load("perplexity", module_type="metric")

def try_compile(program):
    """try to compile the program if correct return 1 else 0 with exception message"""
    try:
        scenarioFromString(program)
        return {"compiled": 1, "exception": ""}
    except Exception as e :
        return {"compiled": 0, "exception": e}
    
def compute_metrics(prediction, reference, model_name):
    return {
        "BLEU": blue_metric.compute(predictions=[prediction],
                                    references=[reference])["bleu"]*100,
        "ROUGE-L": rouge_metric.compute(predictions=[prediction],
                                        references=[reference])["rougeL"]*100,
        "PP": perprexity_metric.compute(predictions=[prediction],
                                        model_id=model_name)["mean_perplexity"],
        "EM": exact_match_metric.compute(predictions=[prediction],
                                         references=[reference])["exact_match"]
        }

def generate_program_from_prompt(cfg, model, tokenizer, prompt):
    """Generate Scenic program from the prompt using the model and tokenizer."""
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(input_ids=inputs["input_ids"].to("cuda"),
                            attention_mask=inputs["attention_mask"].to("cuda"),
                            temperature=cfg.model.temperature,
                            do_sample=cfg.model.do_sample,
                            top_k=cfg.model.decoding_top_k,
                            num_beams=cfg.model.num_beams,
                            max_new_tokens=cfg.model.max_new_tokens)
    pred_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    pred_program = postprocess(pred_output, prompt)

    return pred_program, pred_output

@hydra.main(config_path="../config", config_name="rag", version_base=None)
def main(cfg: DictConfig):

    """Leave one out evaluation for RAG"""

    if cfg.wandb.use_wandb:
        config = OmegaConf.to_container(cfg, resolve=False)
        feed = "-feed" if cfg.model.exceptions.do_feeding else ""
        wandb.init(project=cfg.wandb.project,
                   entity=cfg.wandb.entity,
                   name=f"{cfg.model.model_name}-{cfg.data.evaluation}{feed}",
                   config=config)

    dataset = load_dataset(cfg.data.dataset_name, trust_remote_code=True)

    train_descriptions = dataset['train']['description']
    train_programs = dataset['train']['program']
    train_d2p = {d: p for d, p in zip(train_descriptions, train_programs)}

    test_descriptions = dataset['test']['description']
    test_programs = dataset['test']['program']
    test_d2p = {d: p for d, p in zip(test_descriptions, test_programs)}

    all_d2p = {**train_d2p, **test_d2p}

    # bits and bytes for quantization
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    # LLM model for text generation
    model = AutoModelForCausalLM.from_pretrained(cfg.model.model_name,
                                                device_map="auto",
                                                quantization_config=bnb_config,
                                                torch_dtype=torch.float16,
                                                trust_remote_code=False,
                                                revision="main")
    tokenizer = AutoTokenizer.from_pretrained(cfg.model.model_name, use_fast=True)

    model.eval()

    for target_description, target_program in all_d2p.items():
                
        examplars = retrieve_examplars(target_description,
                                       all_d2p,
                                       cfg.model.retriever_model_name,
                                       cfg.model.similarity_top_k)
        
        prompt = make_prompt(target_description, examplars, all_d2p)
        
        num_trials = 0
        while True:
            num_trials += 1

            pred_program, pred_output = generate_program_from_prompt(cfg, model, tokenizer, prompt)
            compiled = try_compile(pred_program)

            print(compiled["compiled"])
            
            if not compiled["compiled"] and \
                cfg.model.exceptions.do_feeding and \
                num_trials < cfg.model.exceptions.max_trials:
                prompt = add_exception(pred_output, compiled["exception"])
            else:
                break

        ## logging
        if cfg.wandb.use_wandb:
            metrics = compute_metrics(pred_program, target_program, cfg.model.model_name)
            stimuli = {
                "description": wandb.Html(target_description),
                "prompt": wandb.Html(prompt),
                "pred_program": wandb.Html(pred_program),
                "target": wandb.Html(target_program),
            }
            compiled["exception"] =  wandb.Html(str(compiled["exception"]))
            wandb.log({**metrics, **stimuli, **compiled})

if __name__ == "__main__":
    main()
